"use client";
import React, { useState, useEffect, use } from "react";
import Webcam from "react-webcam";
import Image from "next/image";
import { Button } from "../../../../../../components/ui/button";
import SpeechRecognition, { useSpeechRecognition } from 'react-speech-recognition';
import { Mic, MicOff, StopCircle, LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import { generateContent } from "../../../../../../utils/GeminiAIModal.js";
import { db} from "../../../../../../utils/db";
import { UserAnswer } from "../../../../../../utils/schema";
import { useUser } from "@clerk/nextjs";
import moment from 'moment';


function RecordAnswerSection({mockInterviewQuestion,activeQuestionIndex,interviewData}) {
  const [isClient, setIsClient] = useState(false);
  const [userAnswer , setUserAnswer]=useState('');
  const {user}=useUser();
  const [loading,setLoading]=useState(false);
  const [webCamEnabled, setWebCamEnabled] = useState(false);
  const [webCamError, setWebCamError] = useState(false);
  const [micBlocked, setMicBlocked] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);

  const {
    transcript,
    listening: isRecording,
    resetTranscript,
    browserSupportsSpeechRecognition,
    isMicrophoneAvailable
  } = useSpeechRecognition();

  useEffect(() => {
    if (isMicrophoneAvailable === false) {
      setMicBlocked(true);
      toast('Microphone error. Please check your permissions.');
    }
  }, [isMicrophoneAvailable]);

  useEffect(() => {
    if (!isRecording && transcript.length > 10) {
      setUserAnswer(transcript); // Set the answer first
      // UpdateUserAnswer will run automatically because of the next effect if we separate it, 
      // but we can just call it here with the current transcript
      UpdateUserAnswer(transcript);
    }
  }, [isRecording]);

  const StartStopRecording = () => {
    if (!browserSupportsSpeechRecognition) {
      toast("Browser doesn't support speech recognition.");
      return;
    }
    if (isRecording) {
      SpeechRecognition.stopListening();
    } else {
      setMicBlocked(false);
      resetTranscript();
      setUserAnswer('');
      SpeechRecognition.startListening({ continuous: true });
    }
  }

  const UpdateUserAnswer = async (finalTranscript) => {
    console.log(finalTranscript);
    setLoading(true);

    try {
      const feedbackPrompt = `Question: ${mockInterviewQuestion[activeQuestionIndex]?.question}
User Answer: ${finalTranscript}
Based on the question and the user's answer, please provide a rating (from 1 to 10) and feedback for areas of improvement.
CRITICAL INSTRUCTION: The user's answer is generated by a speech-to-text transcriber. You MUST ignore any minor typos, missing punctuation, or incorrect capitalization (e.g. 'begin' instead of 'BigInt'). Focus strictly on the technical content, accuracy, and overall quality of the answer.
Keep the feedback concise (3 to 5 lines).
Return the response in JSON format with "rating" (number) and "feedback" (string) fields only. No additional text or formatting.
Example: {"rating": 8, "feedback": "Good answer but could be more specific about examples."}`;

      const result = await generateContent(feedbackPrompt);

      // Clean up the response to extract JSON
      let cleanedResponse = result.trim();
      cleanedResponse = cleanedResponse.replace(/```json\n?/g, '');
      cleanedResponse = cleanedResponse.replace(/```\n?/g, '');
      
      // Extract JSON part
      const firstBrace = cleanedResponse.indexOf('{');
      const lastBrace = cleanedResponse.lastIndexOf('}');
      if (firstBrace !== -1 && lastBrace !== -1) {
        cleanedResponse = cleanedResponse.substring(firstBrace, lastBrace + 1);
      }
      
      console.log("Cleaned feedback response:", cleanedResponse);
      const JsonFeedbackResp = JSON.parse(cleanedResponse);

      const resp = await db.insert(UserAnswer)
        .values({
          mockIdRef: interviewData?.mockId,
          question: mockInterviewQuestion[activeQuestionIndex]?.question,
          correctAns: mockInterviewQuestion[activeQuestionIndex]?.answer,
          userAns: finalTranscript,
          feedback: JsonFeedbackResp?.feedback,
          rating: JsonFeedbackResp?.rating,
          userEmail: user?.primaryEmailAddress?.emailAddress,
          createdAt: moment().format('DD-MM-yyyy'),
        });

      if (resp) {
        toast('User Answer recorded successfully');
        setUserAnswer('');
        resetTranscript();
      }
    } catch (error) {
      console.error("Error in UpdateUserAnswer:", error);
      toast('Error recording answer. Please try again.');
    } finally {
      resetTranscript();
      setLoading(false);
    }
  }

  if (!isClient) {
    return null; // Return null on the server-side to avoid rendering
  }

  return (
    <div className="flex items-center justify-center flex-col">
      <div className="flex flex-col mt-20 justify-center items-center bg-black rounded-lg p-5 relative overflow-hidden h-[300px] w-full max-w-[500px]">
        {!webCamEnabled && !webCamError && (
          <Image src={"/webcamera.png"} width={200} height={200} className="absolute z-10" alt="Webcam"/>
        )}
        {webCamError && (
          <div className="absolute z-10 text-red-500 text-center font-semibold bg-black p-4 rounded">
            Camera access denied or device not found.<br/>Please enable it in your browser.
            <Button 
              variant="outline" 
              className="mt-4 block mx-auto text-black"
              onClick={async () => {
                 try {
                     await navigator.mediaDevices.getUserMedia({ video: true });
                     setWebCamError(false);
                     setWebCamEnabled(true);
                 } catch(err) {
                     toast('Camera permissions are blocked. Please click the lock icon in your browser to allow access.');
                 }
              }}
            >
              Retry Camera
            </Button>
          </div>
        )}
        <Webcam
          mirrored={true}
          onUserMedia={() => {
            setWebCamEnabled(true);
            setWebCamError(false);
          }}
          onUserMediaError={() => {
            setWebCamEnabled(false);
            setWebCamError(true);
          }}
          style={{
            height: 300,
            width: "100%",
            zIndex: 20,
            opacity: webCamEnabled ? 1 : 0
          }}
        />
      </div>
      <Button 
      disabled={loading}
      variant={isRecording ? "destructive" : micBlocked ? "secondary" : "outline"} 
      className="my-10"
      onClick={StartStopRecording}
    > 
      {loading ? (
        <>
          <LoaderCircle className="animate-spin mr-2" /> Saving Answer...
        </>
      ) : isRecording ? (
        <>
          <StopCircle className="mr-2 animate-pulse" /> Stop Recording
        </>
      ) : micBlocked ? (
        <>
          <MicOff className="mr-2 text-red-500" /> Mic Blocked - Retry
        </>
      ) : (
        <>
          <Mic className="mr-2" /> Record Answer
        </>
      )}
</Button>
    </div>
  );
}

export default RecordAnswerSection;
